# version: '3.8'

# services:
#   db:
#     environment:
#       MYSQL_ROOT_PASSWORD: admin123
#       MYSQL_DATABASE: istory
#       MYSQL_USER: dangtong
#       MYSQL_PASSWORD: admin123
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./data/var/lib/mysql
#     image: mysql:8.0
#     container_name: mysql-container

# volumes:
#   mysql-data:





version: '3'

services:
  db:
    image: mysql:8.0
    container_name: database
    networks:
      - kind_network
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: istory
      MYSQL_USER: dangtong
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
networks:
  kind_network:
    name: kind
    external: true

# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql-container
#     environment:
#       MYSQL_ROOT_PASSWORD: admin123
#       MYSQL_DATABASE: istory
#       MYSQL_USER: root
#       MYSQL_PASSWORD: admin123
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
